### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by Jan-Jan** [MattiLehtinen/postgrator-cli#1]
Thanks for creating posgrator-cli

When I attempt to run `./node_modules/.bin/postgrator` I get the error `env: node\r: No such file or directory`

**Comment by theasp** [comment]
@Jan-Jan you can use `flip -u` or `dos2unix` to fix it

**Comment by MattiLehtinen** [comment]
@Jan-Jan Can you test with latest version if it fixes your problem?

**Comment by jagregory** [comment]
I'm seeing this issue too with the latest version.

It seems to be something to do with the npm package publishing. When I install from npm, I have the issue; but when I install from the repo (e.g. npm install https://github.com/MattiLehtinen/postgrator-cli.git) it works fine.

**Comment by mitskevich** [comment]
I have the same issue on Linux with `postgrator-0.2.0`.

**Comment by Kostanos** [comment]
Same issue here, running on Docker `node:8-alpine` image after `npm install -g postgrator-cli`

Any idea?

**Comment by Kostanos** [comment]
It looks like some OS related issue, as running with command: `node /usr/local/bin/postgrator` it works very well. I compared the head/permissions with other npm apps like nodemon for example, and they are exactly the same as in postgrator. I even commented out all code, and left there simple console.log(..) line

still the same error.

Any other idea?

**Comment by Kostanos** [comment]
```
dos2unix /usr/local/bin/postgrator
```
fixed the issue as mentioned @theasp 

thank you

**Comment by MattiLehtinen** [comment]
Most probably fixed with commit f1dfd7e8a73fe84eedb63ed6436466796406727f

**Comment by MattiLehtinen** [comment]
Thanks everyone for reporting! 

It was npm packaging problem (https://github.com/npm/npm/issues/12371). 0.2.2 has LF line endings ant it should work as expected.
