### ISSUE TITLE
support pg@8?

### ISSUE THREAD

**Issue by adamaiken89** [MattiLehtinen/postgrator-cli#17]
Hi I am trying to run `postgrator-cli` with pg@8 and the cli returns me a message of `Please raise issue to support pg > 7.x.x`. 

`postgrator` looks good to support pg@8 so I think the cli version should be ok too.

**Comment by MattiLehtinen** [comment]
Fixed in d1a1f8182b22c9f87f0c4ab6d0ce43ec64a00469

Will be included in next 4.0.0 release. Note that it will require node >= 10
