### ISSUE TITLE
Can't use absolute directory path in -m option

### ISSUE THREAD

**Issue by mitskevich** [MattiLehtinen/postgrator-cli#3]
It seems that current working directory is [always prepended](https://github.com/MattiLehtinen/postgrator-cli/blob/master/postgrator-cli.js#L56) to the migrations directory provided by the `-m` option. It makes it harder to invoke this command from provision scripts (or any other scripts that can be executed from arbitrary directory).

Example:

```
postgrator -d mydatabase -m /mydb/migrations
```

I expect, that this command will run migrations from `/mydb/migrations`, but instead `posgrator` will look for migrations in `/home/myuser/mydb/migrations` if I run this command from `/home/myuser`.

**Comment by MattiLehtinen** [comment]
Thanks @mitskevich for reporting this! Is fixed for the next version.
