### ISSUE TITLE
CLI does not accept a mixture of config file and command line options

### ISSUE THREAD

**Issue by aaronjameslang** [MattiLehtinen/postgrator-cli#9]
Command line options are ignored

Would a PR be welcome to fix this?

**Comment by aaronjameslang** [comment]
Correction: apparently command line options are ignored completely?

**Comment by MattiLehtinen** [comment]
PR is of course welcome :)

**Comment by perrin4869** [comment]
It is probably irrelevant by now, but this kind of usecase is supported in my fork [`perrin4869/postgrator-cli`](https://www.npmjs.com/package/@perrin4869/postgrator-cli) - see [here](https://github.com/perrin4869/postgrator-cli/blob/c11efba72e4a603ae1feca290cc9849aad9243bc/test/postgrator-cli-tests.js#L181).

**Comment by perrin4869** [comment]
Fixed in #30
